services:
  - type: web
    name: appstore-webhook-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHARED_SECRET
        sync: false
      - key: TEAMS_WEBHOOK_URL
        sync: false
      - key: APP_STORE_URL
        sync: false
      - key: TIMEZONE
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: AZURE_DEVOPS_PAT
        sync: false
      - key: AZURE_DEVOPS_ORG_URL
        sync: false
      - key: AZURE_DEVOPS_PROJECT
        sync: false
      - key: AZURE_DEVOPS_REPO_ID
        sync: false
      - key: AZURE_DEVOPS_SOURCE_BRANCH
        sync: false
      - key: AZURE_DEVOPS_TARGET_BRANCH
        sync: false
      - key: APPLE_EVENT_TRIGGER
        sync: false
